# This is a basic workflow to help you get started with Actions

name: Deploy Surge Website 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop-v2 branch
on:
  push:
    branches: [ develop-v2 ]
  pull_request:
    branches: [ develop-v2 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with: 
          node-version: 12

      # Runs a single command using the runners shell
      - name: Build React App
        run: |
          npm install # Install Dependencies
          CI=false npm run build # CI=false to ignore warnings


      - name: Install Surge
        run: |
          npm install -g surge
          npm run build && mv build/index.html build/200.html && surge build http://9mobility.surge.sh/ --token ${{secrets.SURGE_TOKEN}}
